# -*- coding: utf-8 -*-
"""Codigo_Nivel_Atendimento_SAC_Melhores_Compras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNSHw3CnRvR_rXdj5pGq3FCzOyltjbDC
"""

# Solicita a nota de satisfação do cliente
valor = input("Digite a nota de satisfação (0 a 100): ")

# Validação simples: deve ser só dígitos e estar no intervalo 0..100
if not valor.isdigit():
    print("Valor inválido. Digite um número inteiro entre 0 e 100.")
else:
    nota = int(valor)
    if not 0 <= nota <= 100:
        print("Valor fora do intervalo (0 a 100).")
    elif nota >= 90:
        print("Atendimento de qualidade!")
    elif 70 <= nota <= 89:
        print("Atendimento neutro.")
    else:
        print("Atendimento insatisfatório.")

